name: ticketcher
description: "A Flutter package for creating beautiful ticket-style cards with customizable borders, dividers, and patterns. Perfect for event tickets, boarding passes, and coupons."
version: 1.0.0
homepage: https://github.com/fathialamre/ticketcher
repository: https://github.com/fathialamre/ticketcher
topics:
  - ticket
  - coupon
  - custom-clipper
  - boarding-pass
  - event-ticket


environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
